version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: teamFlow-postgres
    environment:
      - POSTGRES_DB=teamFlowDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes: [ postgres_data:/var/lib/postgresql/data ]
    networks:
      - teamFlow-network

  app:
    build: .
    container_name: teamFlow-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/teamFlowDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8080
      - SPRING_SECURITY_USER_NAME=user
      - SPRING_SECURITY_USER_PASSWORD=q
    depends_on:
      - postgres
    networks:
      - teamFlow-network

volumes:
  postgres_data:


networks:
  teamFlow-network:
    driver: bridge
